version: "3.8"
services:
  nodejs:
    restart: always
    container_name: nodejs_c
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/node
      - /node/node_modules

  redis:
    restart: always
    container_name: redis_c
    build: ./redis
    # image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

  nginx:
    restart: always
    container_name: nginx_c
    build: ./nginx
    ports:
    - '80:80'
    extra_hosts:
    - 'host.docker.internal:192.168.1.249'
    depends_on:
    - nodejs

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.11.4-management
    hostname: rabbitmq
    container_name: rabbitmq_c
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=tim
      - RABBITMQ_DEFAULT_PASS=abcd1234
    # volumes:
    #   - ./data:/var/lib/rabbitmq

  mongodb:
    restart: on-failure:3    
    # image: mongo:4.4.6
    image: mongo:6.0.3
    container_name: mongodb_c
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: tim
    #   MONGO_INITDB_ROOT_PASSWORD: abcd1234
